CREATE DATABASE dbQuanLyKhoThietBi
GO
USE dbQuanLyKhoThietBi
GO
CREATE TABLE NhanVien
(
	MaNV VARCHAR(32) PRIMARY KEY NOT NULL,
	TenNV NVARCHAR(128) NOT NULL,
	MatKhau VARCHAR(256) NOT NULL,
	DienThoai VARCHAR(16),
	DiaChi NVARCHAR(128)
)
GO
CREATE TABLE NhaCungCap
(
	MaNCC VARCHAR(32) PRIMARY KEY NOT NULL,
	TenNCC NVARCHAR(128) NOT NULL,
	DienThoai VARCHAR(16),
	DiaChi NVARCHAR(128)
)
GO
CREATE TABLE LoaiHangHoa
(
	MaLHH VARCHAR(32) PRIMARY KEY NOT NULL,
	TenLHH NVARCHAR(128) NOT NULL
)
GO
CREATE TABLE HangHoa
(
	MaHH VARCHAR(32) PRIMARY KEY NOT NULL,
	TenHH NVARCHAR(128) NOT NULL,
	TonKho DECIMAL NOT NULL,
	DonGia DECIMAL NOT NULL,
	MaNCC VARCHAR(32) FOREIGN KEY REFERENCES NhaCungCap(MaNCC) NOT NULL,
	MaLHH VARCHAR(32) FOREIGN KEY REFERENCES LoaiHangHoa(MaLHH) NOT NULL
)
GO
CREATE TABLE KhachHang
(
	MaKH VARCHAR(32) PRIMARY KEY NOT NULL,
	TenKH NVARCHAR(128) NOT NULL,
	DienThoai VARCHAR(16),
	DiaChi NVARCHAR(128)
)
GO
CREATE TABLE NhapKho
(
	MaHD VARCHAR(32) PRIMARY KEY NOT NULL,
	NgayHD DATETIME NOT NULL,
	MaNV VARCHAR(32) FOREIGN KEY REFERENCES NhanVien(MaNV) NOT NULL,
	TongTien decimal NOT NULL,
)
GO
CREATE TABLE ChiTietNhapKho
(
	MaHD VARCHAR(32) FOREIGN KEY REFERENCES NhapKho(MaHD) NOT NULL,
	MaHH VARCHAR(32) FOREIGN KEY REFERENCES HangHoa(MaHH) NOT NULL,
	DonGia decimal NOT NULL,
	SoLuong decimal NOT NULL,
	ThanhTien decimal NOT NULL
)
GO
CREATE TABLE XuatKho
(
	MaHD VARCHAR(32) PRIMARY KEY NOT NULL,
	MaKH VARCHAR(32) FOREIGN KEY REFERENCES khachhang(makh) NOT NULL,
	NgayBan DATETIME NOT NULL,
	MaNV VARCHAR(32) FOREIGN KEY REFERENCES nhanvien(manv) NOT NULL,
	TongTien DECIMAL NOT NULL,
	TrangThai NVARCHAR(128) NOT NULL
)
GO
CREATE TABLE ChiTietXuatKho
(
	MaHD VARCHAR(32) FOREIGN KEY REFERENCES XuatKho(MaHD) NOT NULL,
	MaHH VARCHAR(32) FOREIGN KEY REFERENCES HangHoa(MaHH) NOT NULL,
	DonGia DECIMAL NOT NULL,
	SoLuong DECIMAL NOT NULL,
	ThanhTien DECIMAL NOT NULL
)
INSERT INTO NhanVien (MaNV,TenNV,MatKhau,DienThoai,DiaChi)VALUES(N'AD',N'ADMIN',N'123456',N'0354784521',N'TPHCM')
GO
INSERT INTO LoaiHangHoa (MaLHH,TenLHH)VALUES(N'DOGIADUNG',N'Đồ gia dụng')
INSERT INTO LoaiHangHoa (MaLHH,TenLHH)VALUES(N'THIETBIDIEN',N'Thiết bị điện')
GO
INSERT INTO NhaCungCap (MaNCC,TenNCC,DienThoai,DiaChi)VALUES(N'CTYHP',N'Công ty Hoàng Phong',N'0354125854',N'TPHCM')
INSERT INTO NhaCungCap (MaNCC,TenNCC,DienThoai,DiaChi)VALUES(N'CTYOFF',N'Công ty Officexinh',N'0241524124',N'TPHCM')
GO
INSERT INTO HangHoa (MaHH,TenHH,TonKho,DonGia,MaNCC,MaLHH)VALUES(N'DENLED',N'Đèn led',10051,58000,N'CTYHP',N'THIETBIDIEN')
INSERT INTO HangHoa (MaHH,TenHH,TonKho,DonGia,MaNCC,MaLHH)VALUES(N'OCAMDIEN',N'Ổ cắm điện',10002,80000,N'CTYHP',N'THIETBIDIEN')
GO
INSERT INTO KhachHang (MaKH,TenKH,DienThoai,DiaChi)VALUES(N'KH001',N'Công Lâm',N'0541256526',N'TPHCM')
INSERT INTO KhachHang (MaKH,TenKH,DienThoai,DiaChi)VALUES(N'KH002',N'Vũ Mạnh',N'0124545263',N'TPHCM')

